### ISSUE TITLE
Some missing parts

### ISSUE THREAD

**Issue by YanYu96** [Tinbeh97/Graph_ML#1]
1. "from evaluation import EER_calculation" Where is the file of evaluation? Can you share it? 

2. What are the values corresponding to self.hd1, self.hd2, and self.hd3?

**Comment by Tinbeh97** [comment]
I added the evaluation.py file. 

hd1, hd2, hd3 are hidden layers' sizes and their values depend on your input data and desired model structure that is why there are no value corresponding to them here. If you want to use the dimensions that I used, check out my paper. You can find the full distribution there.
